### ISSUE TITLE
nic driver stopped working

### ISSUE THREAD

**Issue by BugUser0815** [702nADOS/genode#14]
@StefanEdingerTUM Now there is another problem. I have no clue how this is related to your changes of the cpu thread component, but now the nic driver stopped working. Before your changes genode printed the following lines if dom0-HW was executed:
[init -> nic_drv] id/rev:      0x1180001
[init -> nic_drv] byte order:  0x87654321
[init -> nic_drv] MAC address: 01:01:00:00:00:02
But now they are not there anymore. Do you have any idea how this happened?

**Comment by BugUser0815** [comment]
The line
Alarm::Time starttime = Timeout_thread::alarm_timer()->time();
within
genode/repos/libports/src/lib/lwip/platform/sys_arch.cc
causes the error. No clue why.

**Comment by StefanEdingerTUM** [comment]
I have also no idea why this is the case...

**Comment by BugUser0815** [comment]
Quick dirty fix:
Alarm::Time starttime = 0;
