### ISSUE TITLE
Creation of edf threads not successful

### ISSUE THREAD

**Issue by BugUser0815** [702nADOS/genode#22]
@dk87  I wanted to use the create_fp_ed_thread method written by @StefanEdingerTUM for deploying and monitoring cores and queues other than 0 and fp.
But I constantly get "wrong scheduling type".
I already took a look at the merge of focnados_api, which was Stefan's branch for his IDP, into focnados.
Until today there were no changes made to create_fp_edf_thread.

**Comment by BugUser0815** [comment]
Update:
The output of the fp-edf-test with the current genode commit, as well as with commit "Merge focnados_api into focnados" https://github.com/argos-research/genode/commit/f31073ab1aa15d89d3d118c4bdc14587be0836d7 looks as follows:

[init -> fp-edf-test] --- thread test started ---
[init -> fp-edf-test] affinity space: 2
wrong scheduling type
wrong scheduling type
wrong scheduling type
wrong scheduling type
wrong scheduling type
wrong scheduling type
wrong scheduling type
wrong scheduling type
wrong scheduling type
Wrong Scheduling Type on CPU 0, expected Fixed Priority
[init -> fp-edf-test] Catched exception, Thread creation failed
Wrong Scheduling Type on CPU 1, expected EDF
[init -> fp-edf-test] Catched exception, Thread creation failed

If I change line 427 of platform_thread.cc from
_prio(Cpu_session::scale_priority(DEFAULT_PRIORITY, prio)) to
_prio(prio)

The output of fp-test-test looks like this:

[init -> fp-edf-test] --- thread test started ---
[init -> fp-edf-test] affinity space: 2
[Scheduler::sys_run] Deadline passed for id:9d is: 4
[Ready_queue_edf::enqueue] Inserted id:9d at front
edf_rq: 9d(dl:4) => end
[Scheduler::sys_run] Deadline passed for id:9d is: 4
[Ready_queue_edf::enqueue] Inserted id:9d (same deadline: 4)
edf_rq: 9d(dl:4) => end
[Scheduler::sys_run] Deadline passed for id:9d is: 4
[Ready_queue_edf::enqueue] Inserted id:9d (same deadline: 4)
edf_rq: 9d(dl:4) => end
[Scheduler::sys_run] Deadline passed for id:a1 is: 3
[Ready_queue_edf::enqueue] Inserted id:a1 (different deadlines: 3 vs. 4)
edf_rq: a1(dl:3) => 9d(dl:4) => end
[Scheduler::sys_run] Deadline passed for id:a1 is: 3
[Ready_queue_edf::enqueue] Inserted id:a1 (same deadline: 3)
edf_rq: a1(dl:3) => end
[Scheduler::sys_run] Deadline passed for id:a1 is: 3
[Ready_queue_edf::enqueue] Inserted id:a1 (same deadline: 3)
edf_rq: a1(dl:3) => end
[Scheduler::sys_run] Deadline passed for id:a5 is: 2
[Ready_queue_edf::enqueue] Inserted id:a5 (different deadlines: 2 vs. 3)
edf_rq: a5(dl:2) => a1(dl:3) => end
[Scheduler::sys_run] Deadline passed for id:a5 is: 2
[Ready_queue_edf::enqueue] Inserted id:a5 (same deadline: 2)
edf_rq: a5(dl:2) => end
[Scheduler::sys_run] Deadline passed for id:a5 is: 2
[Ready_queue_edf::enqueue] Inserted id:a5 (same deadline: 2)
edf_rq: a5(dl:2) => end
Wrong Scheduling Type on CPU 0, expected Fixed Priority
[init -> fp-edf-test] Catched exception, Thread creation failed
Wrong Scheduling Type on CPU 1, expected EDF
[init -> fp-edf-test] Catched exception, Thread creation failed

To me the second result looks way more legit, than the first one.
Should this line be changed, or am I missing something?

**Comment by StefanEdingerTUM** [comment]
The wrong scheduling type is caused by the platform_thread. 
There it is expected that one of the parameters prio or deadline is smaller or equal 0. 
Does the system also work with FP tasks if you change the priority assignement?

**Comment by BugUser0815** [comment]
The wrong scheduling type occurs, because your implementation causes none of the parameters of an edf thread to be 0.
The line Cpu_session::scale_priority(DEFAULT_PRIORITY, prio) with prio=0 evaluates to 128.
So create_fp_edf_thread(prio=0, deadline=1) has prio=128 and deadline=1 once it reaches the platform_thread constructor. -> wrong scheduling type
If I change the line, both kind of tasks can be created, but then the priority is not interpreted correctly.
I could also change your test to create_fp_edf_thread(prio=65536, deadline=1) which evaluates to prio=0 and deadline=1 with your platform_thread constructor.
Both cases make no sense. What should I do?

**Comment by BugUser0815** [comment]
Fixed. Implementation checks for edf first now. Error went away.
