### ISSUE TITLE
focnados branch: vagrant up error stdin is no tty

### ISSUE THREAD

**Issue by ghost** [702nADOS/genode#7]
@privatereese @BugUser0815 there is an error during vagrant up:

`==> default: mesg: ttyname failed: Inappropriate ioctl for device`

Any idea?

**Comment by BugUser0815** [comment]
@dk87 
@privatereese told me to ignore this message

**Comment by ghost** [comment]
okay found the following https://github.com/mitchellh/vagrant/issues/7155#issuecomment-228568200
It seems the bento packages are more robust than the ubuntu ones.

I'm trying it at the moment :)

**Comment by privatereese** [comment]
yes please ignore it. @irgendwie and @BugUser0815  did also come along this error message but it doesnt change anything and cannot be fixed so quickly, btw. ssh is via command "vagrant ssh" in the git folder of the vagrant file and all in that folder is shared to /vagrant/ and no hardlinks are allowed in there as i know from @BugUser0815 , dont try bento boxes same error @irgendwie has done it before!

**Comment by ghost** [comment]
Ah okay I thought it was my fault :-). Thank you @privatereese but the machine hangs at this error so ...

**Comment by ghost** [comment]
So, I close this issue because it seems to be a problem with vagrant rather than our build process.

**Comment by irgendwie** [comment]
@dk87 not sure if it really hangs, try without provision and bootstrap and wait after the error for some time - normally it just boots up correctly and one can use 'vagrant ssh' afterwards
